### ISSUE TITLE
AnteHandler changes cause panic

### ISSUE THREAD

**Issue by Senna46** [sunriselayer/gluon#5]
The `sealed` flag in baseapp is true when the app should not be modified further. It is set when `baseapp.Init()` or `baseapp.Seal()` are called.

```panic: SetAnteHandler() on sealed BaseApp
goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).SetAnteHandler(...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.10/baseapp/options.go:225
gluon/app.New({0x4a2e4a0, 0xc00124a770}, {0x4a4c260, 0xc000864058}, {0x0, 0x0}, 0x1, {0x49dca20, 0xc0012da540}, {0xc00124a4d0, ...})
        /root/gluon/app/app.go:356 +0x11a5```

**Comment by Senna46** [comment]
Soved with 9b1fea44649f7cffee6e5e3a21ef0110dc0e2d20
